name: Gradle Publish to Private Maven
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 23
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 23
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish to Maven
        env:
          TAG_VERSION: ${{ github.ref_name }}
        run: |
          ./gradlew publishAllPublicationsToReleaseRepository
          echo "Version: ${TAG_VERSION}" >> $GITHUB_STEP_SUMMARY
